security:
    acl:
        connection: default
        cache:
            id: security.acl.cache.doctrine
            prefix: sf2_acl_

    firewalls:
        main:
            http_basic:
                realm: "Secured REST Area"
            provider: oro_user
            form_login: false
            logout: false
            remember_me: false
            anonymous: true
